import argparse
import numpy as np
import pandas as pd
from scipy.sparse import csr_matrix
from sklearn.decomposition import NMF, LatentDirichletAllocation
from torch.utils.data import DataLoader
from transformers import AutoTokenizer  # <-- ADDED THIS

# Import your existing dataloaders
from dataload_SemEval import get_semeval_data, LLRDataset

def print_top_words(model_name, topic_word_matrix, tokenizer, n_top_words=15):
    """Helper function to print the topics generated by the baselines."""
    print(f"\n{'='*50}")
    print(f" {model_name} TOP WORDS (Raw BERT Subwords)")
    print(f"{'='*50}")
    for topic_idx, topic in enumerate(topic_word_matrix):
        # Get the indices of the top words
        top_indices = topic.argsort()[:-n_top_words - 1:-1]
        
        # <-- FIXED THIS: Use HuggingFace tokenizer to convert exact IDs back to strings
        # This will perfectly expose the '##' subword fragments!
        top_words = [tokenizer.convert_ids_to_tokens(int(i)) for i in top_indices]
        
        print(f"Topic #{topic_idx}: {' '.join(top_words)}")
    print("="*50)

def main():
    parser = argparse.ArgumentParser(description="Apples-to-Apples Baseline Test on BERT Subwords")
    parser.add_argument('--dataset', type=str, default='semeval14_rest')
    parser.add_argument('--train_path', type=str, required=True)
    parser.add_argument('--test_path', type=str, required=True)
    parser.add_argument('--model_name_or_path', type=str, default='bert-base-uncased')
    parser.add_argument('--num_aspects', type=int, default=5)
    args = parser.parse_args()

    # Load the HuggingFace Tokenizer natively
    tokenizer = AutoTokenizer.from_pretrained(args.model_name_or_path)

    # 1. Load data EXACTLY as MAB-LDA does
    print(f"Loading data via BERT tokenizer ({args.model_name_or_path})...")
    df_train, tokens, aspect_cols = get_semeval_data(args.train_path, args.model_name_or_path)
    df_test, _, _ = get_semeval_data(args.test_path, args.model_name_or_path)
    df = pd.concat([df_train, df_test], ignore_index=True)

    dataset = LLRDataset(df, None)
    # Load everything into one massive batch to build the matrix
    dataloader = DataLoader(dataset, batch_size=len(dataset), shuffle=False)
    
    for _, (idx, data1) in enumerate(dataloader):
        doc_tensors = data1[0].numpy()  # Shape: [N_docs, Max_Seq_Len]
        break

    # 2. Extract the PAD token ID to ignore padding
    PAD_TOKEN_ID = tokenizer.pad_token_id
    vocab_size = int(doc_tensors.max()) + 1
    n_docs = doc_tensors.shape[0]

    # 3. Construct the Sparse Document-Term Matrix (DTM)
    print("\nConstructing exact Document-Term Matrix from subword tensors...")
    rows, cols, vals = [], [], []
    
    for d in range(n_docs):
        for w_int in doc_tensors[d]:
            if w_int == PAD_TOKEN_ID:
                break  # Stop processing at the padding token
            rows.append(d)
            cols.append(w_int)
            vals.append(1)  # Count frequency

    # Create the sparse matrix for scikit-learn
    X_subwords = csr_matrix((vals, (rows, cols)), shape=(n_docs, vocab_size))
    
    print(f"Matrix shape: {X_subwords.shape} | Non-zero elements: {X_subwords.nnz}")

    # 4. Execute Baselines on the Subword Matrix
    print("\nTraining Standard LDA on BERT Subwords...")
    lda_model = LatentDirichletAllocation(n_components=args.num_aspects, random_state=42, max_iter=20)
    lda_model.fit(X_subwords)
    print_top_words("STANDARD LDA", lda_model.components_, tokenizer)

    print("\nTraining NMF on BERT Subwords...")
    nmf_model = NMF(n_components=args.num_aspects, random_state=42, max_iter=500)
    nmf_model.fit(X_subwords)
    print_top_words("NMF", nmf_model.components_, tokenizer)

if __name__ == '__main__':
    main()
